[package]
name = "{{ name | kebab_case }}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
keywords.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[features]
default = []
profiling = ["dep:dhat", "mhub-logger/profiling"]
full = ["default"]

[dependencies]
mhub-logger.workspace = true
mhub-runtime.workspace = true
mhub.workspace = true
mhub-error = { workspace = true, features = ["std", "json"] }

dhat = { workspace = true, optional = true }

[[bin]]
name = "{{ shortname | kebab_case }}"
path = "src/main.rs"

[lib]
name = "{{ name | snake_case }}"
path = "src/lib.rs"

[lints]
workspace = true
